routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();
// Example Routes
Route::view('/', 'landing');

Route::middleware('auth')->group(function () {
  Route::match(['get', 'post'], '/dashboard', function(){return view('dashboard');});
});

Route::middleware(['auth', 'seller'])->group(function () {
  Route::view('/create-order', 'create_order');
  Route::resource('new_order','OrderController');
});

Route::middleware('auth')->group(function () {
  Route::get('/view-orders', 'OrderController@show');
  Route::get('/view-orders/{id}', 'OrderController@edit');
  Route::resource('new_order','OrderController');
});

app/Order.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
  protected $fillable = [
      'product_name', 'priority', 'order_status','office','payment_type','product_weight','product_quantity','customer_name','customer_phone','customer_address'
  ];


}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','role'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('dashboard');
    }
}

app/Http/Controllers/OrderController.php
<?php

namespace App\Http\Controllers;

use App\Order;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Auth;
use Response;

class OrderController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      $this->validate($request, [
          'product_title' => ['required', 'string', 'max:255'],
          'priority' => ['required'],
          'order_status' => ['required'],
          'office' => ['required','string'],
          'payment_type' => ['required'],
          'product_weight' => ['required'],
          'product_quantity' => ['required'],
          'customer_name' => ['required','string'],
          'customer_mobile_number' => ['required'],
          'customer_address' => ['required','string'],
      ]);
      $order_id = $request->order_id;
      $order =   Order::updateOrCreate(['id' => $order_id],
                ['product_name' => $request->product_title,
                 'priority' => $request->priority,
                 'order_status' => $request->order_status,
                 'office' => $request->office,
                 'payment_type' => $request->payment_type,
                 'product_weight' => $request->product_weight,
                 'product_quantity' => $request->product_quantity,
                 'customer_name' => $request->customer_name,
                 'customer_phone' => $request->customer_mobile_number,
                 'customer_address' => $request->customer_address,
               ]);
        if(!empty($order)){
          $msg = array('msg'=>['added succesfully!'],'type'=>['success']);
        }else{
          $msg = array('msg'=>['Somithing went wrong!'],'type'=>['error']);
        }

      return Response::json($msg);
}

    /**
     * Display the specified resource.
     *
     * @param  \App\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function show(Order $order)
    {
        if (Auth::user()->role == 'Operations') {
           $data = Order::where('approved', 1)->get();

       }elseif(Auth::user()->role == 'CS'){
            $data = Order::where('approved', 0)->get();
       }elseif(Auth::user()->role == 'Admin'){
            $data = Order::all()->first()->get();
       }
         return view('view_orders')->with('showAllOrder', $data);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function edit($order_id)
    {
      if(Auth::user()->role == 'CS'){
        $update = Order::where('id', $order_id)->update(['approved' => 1]);
        $data = Order::where('approved', 0)->get();
        return view('view_orders')->with('showAllOrder', $data);
     }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Order $order)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function destroy(Order $order)
    {
        //
    }
}

resources/views/create_order.blade.php
@extends('layouts.backend')

@section('content')
<!-- Main Container -->

<!-- Main Container -->

                <!-- Page Content -->
                <div class="content">
                    <!-- Basic -->
                    <div class="block">
                        <h3 class="block-title">Create Order</h3>
                        <div class="block-content block-content-full">
                                <div class="row push">


                                    <div class="col-lg-12 col-xl-12">
                                        <form id="createOrder" >
                                        <div class="form-group error">
                                            <label for="example-text-input">Product Title</label>
                                            <input type="text" class="form-control" id="product_title" name="product_title" placeholder="Enter The Product Name">
                                        </div>
                                         <div class="form-group error">
                                            <label for="example-select">Priority</label>
                                            <select class="form-control" id="priority" name="priority">
                                                <option selected="selected" disabled="true">Please select</option>
                                                <option >On Demand</option>
                                                <option >Same Day</option>
                                                <option >Next Day</option>
                                            </select>
                                        </div>

                                        <div class="form-group error">
                                            <label for="example-select">Order Status</label>
                                            <select class="form-control" id="order_status" name="order_status">
                                                <option selected="selected" disabled="true">Please select</option>
                                                <option >Pending</option>
                                            </select>
                                        </div>

                                        <div class="form-group error">
                                            <label for="example-select">Hub</label>
                                            <select class="form-control " id="office" name="office">
                                                <option selected="selected" disabled="true">Please select</option>
                                                <option >New Market</option>
                                                <option >Mirpur</option>
                                                <option >Uttara</option>
                                            </select>
                                        </div>
                                         <div class="form-group error">
                                            <label for="example-select">Payment Type</label>
                                            <select class="form-control " id="payment_type" name="payment_type">
                                                <option selected="selected" disabled="true">Please select</option>
                                                <option >Cash On Delivery</option>
                                                <option >Pay In Online</option>
                                            </select>
                                        </div>
                                          <div class="form-group error">
                                            <label for="example-text-input">Product Weight</label>
                                            <input type="number" class="form-control " id="product_weight" name="product_weight" placeholder="Enter The Product Weight">
                                        </div>

                                          <div class="form-group error" >
                                            <label for="example-text-input">Product Quantity</label>
                                            <input type="text" class="form-control " id="product_quantity" name="product_quantity" placeholder="Enter The Product Quantity">
                                        </div>

                                          <div class="form-group error">
                                            <label for="example-text-input">Customer Name</label>
                                            <input type="text" class="form-control " id="customer_name" name="customer_name" placeholder="Enter The Customer Name">
                                        </div>

                                          <div class="form-group error">
                                            <label for="example-text-input">Customer Mobile Number</label>
                                            <input type="text" class="form-control " id="customer_mobile_number" name="customer_mobile_number" placeholder="Enter The Customer Mobile Number">
                                        </div>

                                            <div class="form-group error">
                                            <label for="example-text-input">Customer Address</label>
                                            <input type="text" class="form-control " id="customer_address" name="customer_address" placeholder="Enter The Customer Address">
                                        </div>

                                         <div class="col-sm-12 col-xl-12">
                                        <button type="submit" id="submit" class="btn btn-success">Submit</button>
                                        <div class="mt-12">
                                            <!-- <code>btn-success</code> -->
                                        </div>
                                    </div>


                                  </form>
                                    </div>
                                </div>
                        </div>
                    </div>

                </div>
                <!-- END Page Content -->


            <!-- END Main Container -->
@endsection

@section('js_after')
<script type="text/javascript">

     $(document).on('keyup change','.form-control', function() {
         var err_id = $(this).attr('id');
         $('#' + err_id).closest('.form-control').removeClass('is-invalid');
         $('#' + err_id).closest('.error').find('.error-block').remove();
     });
     function resetform(){
          $('#createOrder').trigger("reset");
          ok();
    }
     function ok(){
         formdata = $('#createOrder');
         formdata.find('.error-block').remove();
         formdata.find('.form-control').removeClass('is-invalid');
     }
     // ajax insertion and error handling
     $('#submit').click(function (event) {
         event.preventDefault();
         ok();
         $.ajax({
             url : "{{route('new_order.store')}}",
             headers: {'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')},
             type: "POST",
             data : formdata.serialize(),
             success: function (response) {

               Swal.fire({
                   title: response.msg,
                   icon:  response.type,
                   showCancelButton: false,//There won't be any cancle button
                   showConfirmButton  : false,
                   timer: 1500
                 });
                 resetform();
             },
             error : function (xhr) {
                 var res = xhr.responseJSON;
                //console.log(res)
                 if ($.isEmptyObject(res) == false) {
                     $.each(res.errors, function (key, value) {
                         //console.log(value)
                         $('#' + key)
                             .closest('.error')
                             .append('<div class="invalid-feedback animated fadeIn" ><strong>' + value + '</strong></div>');

                         $('#' + key)
                             .closest('.form-control')
                             .addClass('is-invalid');
                     });
                 }
             }
         })
     });

</script>
@endsection

resources/views/dashboard.blade.php
@extends('layouts.backend')

@section('content')
<!-- Main Container -->
       <main id="main-container">
           <!-- Hero -->
           <div class="bg-image overflow-hidden" style="background-image: url('assets/media/photos/photo3@2x.jpg');">
               <div class="bg-primary-dark-op">
                   <div class="content content-narrow content-full">
                       <div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center mt-5 mb-2 text-center text-sm-left">
                           <div class="flex-sm-fill">
                               <h1 class="font-w600 text-white mb-0 invisible" data-toggle="appear">Dashboard</h1>
                           </div>
                           <div class="flex-sm-00-auto mt-3 mt-sm-0 ml-sm-3">
                               <span class="d-inline-block invisible" data-toggle="appear" data-timeout="350">
                               </span>
                           </div>
                       </div>
                   </div>
               </div>
           </div>
           <!-- END Hero -->
           <!-- Page Content -->
           <div class="content content-narrow">
               <!-- Stats -->
               <div class="row">
                   <div class="col-6 col-md-3 col-lg-6 col-xl-3">
                       <a class="block block-rounded block-link-pop border-left border-primary border-4x" href="javascript:void(0)">
                           <div class="block-content block-content-full">
                               <div class="font-size-sm font-w600 text-uppercase text-muted">All Order</div>
                               <div class="font-size-h2 font-w400 text-dark">120</div>
                           </div>
                       </a>
                   </div>
                   <div class="col-6 col-md-3 col-lg-6 col-xl-3">
                       <a class="block block-rounded block-link-pop border-left border-primary border-4x" href="javascript:void(0)">
                           <div class="block-content block-content-full">
                               <div class="font-size-sm font-w600 text-uppercase text-muted">Sales</div>
                               <div class="font-size-h2 font-w400 text-dark">150</div>
                           </div>
                       </a>
                   </div>
                   <div class="col-6 col-md-3 col-lg-6 col-xl-3">
                       <a class="block block-rounded block-link-pop border-left border-primary border-4x" href="javascript:void(0)">
                           <div class="block-content block-content-full">
                               <div class="font-size-sm font-w600 text-uppercase text-muted">Earnings</div>
                               <div class="font-size-h2 font-w400 text-dark">3,200</div>
                           </div>
                       </a>
                   </div>
                   <div class="col-6 col-md-3 col-lg-6 col-xl-3">
                       <a class="block block-rounded block-link-pop border-left border-primary border-4x" href="javascript:void(0)">
                           <div class="block-content block-content-full">
                               <div class="font-size-sm font-w600 text-uppercase text-muted">Avg Sale</div>
                               <div class="font-size-h2 font-w400 text-dark">21</div>
                           </div>
                       </a>
                   </div>
               </div>
               <!-- END Stats -->
           </div>
           <!-- END Page Content -->
       </main>
       <!-- END Main Container -->
@endsection

resources/views/examples/blank.blade.php
@extends('layouts.backend')

@section('content')
    <!-- Hero -->
    <div class="bg-body-light">
        <div class="content content-full">
            <div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center">
                <h1 class="flex-sm-fill h3 my-2">
                    Main Title <small class="d-block d-sm-inline-block mt-2 mt-sm-0 font-size-base font-w400 text-muted">Subtitle</small>
                </h1>
                <nav class="flex-sm-00-auto ml-sm-3" aria-label="breadcrumb">
                    <ol class="breadcrumb breadcrumb-alt">
                        <li class="breadcrumb-item">Examples</li>
                        <li class="breadcrumb-item" aria-current="page">
                            <a class="link-fx" href="">Blank</a>
                        </li>
                    </ol>
                </nav>
            </div>
       </div>
    </div>
    <!-- END Hero -->

    <!-- Page Content -->
    <div class="content">
        <!-- Your Block -->
        <div class="block">
            <div class="block-header">
                <h3 class="block-title">Block Title</h3>
            </div>
            <div class="block-content">
                <p class="font-size-sm text-muted">
                    Your content..
                </p>
            </div>
        </div>
        <!-- END Your Block -->
    </div>
    <!-- END Page Content -->
@endsection

resources/views/examples/plugin_helper.blade.php
@extends('layouts.backend')

@section('css_before')
    <link rel="stylesheet" href="{{ asset('js/plugins/slick-carousel/slick.css') }}">
    <link rel="stylesheet" href="{{ asset('js/plugins/slick-carousel/slick-theme.css') }}">
@endsection

@section('js_after')
    <!-- Page JS Plugins -->
    <script src="{{ asset('js/plugins/slick-carousel/slick.min.js') }}"></script>

    <!-- Page JS Helpers (Slick Slider Plugin) -->
    <script>jQuery(function(){ One.helpers('slick'); });</script>
@endsection

@section('content')
    <!-- Hero -->
    <div class="bg-body-light">
        <div class="content content-full">
            <div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center">
                <h1 class="flex-sm-fill h3 my-2">
                    Slick Slider Example <small class="d-block d-sm-inline-block mt-2 mt-sm-0 font-size-base font-w400 text-muted">Plugin Integration</small>
                </h1>
                <nav class="flex-sm-00-auto ml-sm-3" aria-label="breadcrumb">
                    <ol class="breadcrumb breadcrumb-alt">
                        <li class="breadcrumb-item">Examples</li>
                        <li class="breadcrumb-item" aria-current="page">
                            <a class="link-fx" href="">Plugin</a>
                        </li>
                    </ol>
                </nav>
            </div>
       </div>
    </div>
    <!-- END Hero -->

    <!-- Page Content -->
    <div class="content">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <!-- Info -->
                <div class="block">
                    <div class="block-header">
                        <h3 class="block-title">Plugin Example</h3>
                    </div>
                    <div class="block-content">
                        <p class="font-size-sm text-muted">
                            This page showcases how easily you can add a plugin’s JS/CSS assets and init it using a OneUI JS helper.
                        </p>
                    </div>
                </div>
                <!-- END Info -->

                <!-- Slider with dots -->
                <div class="block">
                    <div class="block-header">
                        <h3 class="block-title">Dots</h3>
                    </div>
                    <div class="js-slider" data-dots="true">
                        <div>
                            <img class="img-fluid" src="{{ asset('media/photos/photo27@2x.jpg')}}" alt="photo">
                        </div>
                        <div>
                            <img class="img-fluid" src="{{ asset('media/photos/photo28@2x.jpg')}}" alt="photo">
                        </div>
                        <div>
                            <img class="img-fluid" src="{{ asset('media/photos/photo29@2x.jpg')}}" alt="photo">
                        </div>
                    </div>
                    <!-- END Slider with dots -->
                </div>
                <!-- END Dots -->
            </div>
        </div>
    </div>
    <!-- END Page Content -->
@endsection

resources/views/examples/plugin_init.blade.php
@extends('layouts.backend')

@section('css_before')
    <!-- Page JS Plugins CSS -->
    <link rel="stylesheet" href="{{ asset('js/plugins/datatables/dataTables.bootstrap4.css') }}">
    <link rel="stylesheet" href="{{ asset('js/plugins/datatables/buttons-bs4/buttons.bootstrap4.min.css') }}">
@endsection

@section('js_after')
    <!-- Page JS Plugins -->
    <script src="{{ asset('js/plugins/datatables/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('js/plugins/datatables/dataTables.bootstrap4.min.js') }}"></script>
    <script src="{{ asset('js/plugins/datatables/buttons/dataTables.buttons.min.js') }}"></script>
    <script src="{{ asset('js/plugins/datatables/buttons/buttons.print.min.js') }}"></script>
    <script src="{{ asset('js/plugins/datatables/buttons/buttons.html5.min.js') }}"></script>
    <script src="{{ asset('js/plugins/datatables/buttons/buttons.flash.min.js') }}"></script>
    <script src="{{ asset('js/plugins/datatables/buttons/buttons.colVis.min.js') }}"></script>

    <!-- Page JS Code -->
    <script src="{{ asset('js/pages/tables_datatables.js') }}"></script>
@endsection

@section('content')
    <!-- Hero -->
    <div class="bg-body-light">
        <div class="content content-full">
            <div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center">
                <h1 class="flex-sm-fill h3 my-2">
                    DataTables Example <small class="d-block d-sm-inline-block mt-2 mt-sm-0 font-size-base font-w400 text-muted">Plugin Integration</small>
                </h1>
                <nav class="flex-sm-00-auto ml-sm-3" aria-label="breadcrumb">
                    <ol class="breadcrumb breadcrumb-alt">
                        <li class="breadcrumb-item">Examples</li>
                        <li class="breadcrumb-item" aria-current="page">
                            <a class="link-fx" href="">Plugin</a>
                        </li>
                    </ol>
                </nav>
            </div>
       </div>
    </div>
    <!-- END Hero -->

    <!-- Page Content -->
    <div class="content">
        <!-- Info -->
        <div class="block">
            <div class="block-header">
                <h3 class="block-title">Plugin Example</h3>
            </div>
            <div class="block-content">
                <p class="font-size-sm text-muted">
                    This page showcases how easily you can add a plugin’s JS/CSS assets and init it using custom JS code.
                </p>
            </div>
        </div>
        <!-- END Info -->

        <!-- Dynamic Table Full -->
        <div class="block">
            <div class="block-header">
                <h3 class="block-title">Dynamic Table <small>Full</small></h3>
            </div>
            <div class="block-content block-content-full">
                <!-- DataTables init on table by adding .js-dataTable-full class, functionality is initialized in js/pages/tables_datatables.js -->
                <table class="table table-bordered table-striped table-vcenter js-dataTable-full">
                    <thead>
                        <tr>
                            <th class="text-center" style="width: 80px;">#</th>
                            <th>Name</th>
                            <th class="d-none d-sm-table-cell" style="width: 30%;">Email</th>
                            <th style="width: 15%;">Registered</th>
                        </tr>
                    </thead>
                    <tbody>
                        @for ($i = 1; $i < 21; $i++)
                        <tr>
                            <td class="text-center"><?php echo $i; ?></td>
                            <td class="font-w600">
                                <a href="javascript:void(0)">John Doe</a>
                            </td>
                            <td class="d-none d-sm-table-cell">
                                client{{ $i }}<em class="text-muted">@example.com</em>
                            </td>
                            <td>
                                <em class="text-muted">{{ rand(2, 10) }} days ago</em>
                            </td>
                        </tr>
                        @endfor
                    </tbody>
                </table>
            </div>
        </div>
        <!-- END Dynamic Table Full -->

        <!-- Dynamic Table with Export Buttons -->
        <div class="block">
            <div class="block-header">
                <h3 class="block-title">Dynamic Table <small>Export Buttons</small></h3>
            </div>
            <div class="block-content block-content-full">
                <!-- DataTables init on table by adding .js-dataTable-buttons class, functionality is initialized in js/pages/tables_datatables.js -->
                <table class="table table-bordered table-striped table-vcenter js-dataTable-buttons">
                    <thead>
                        <tr>
                            <th class="text-center" style="width: 80px;">#</th>
                            <th>Name</th>
                            <th class="d-none d-sm-table-cell" style="width: 30%;">Email</th>
                            <th style="width: 15%;">Registered</th>
                        </tr>
                    </thead>
                    <tbody>
                        @for ($i = 1; $i < 21; $i++)
                        <tr>
                            <td class="text-center">{{ $i }}</td>
                            <td class="font-w600">
                                <a href="javascript:void(0)">John Smith</a>
                            </td>
                            <td class="d-none d-sm-table-cell">
                                client{{ $i }}<em class="text-muted">@example.com</em>
                            </td>
                            <td>
                                <em class="text-muted">{{ rand(2, 10) }} days ago</em>
                            </td>
                        </tr>
                        @endfor
                    </tbody>
                </table>
            </div>
        </div>
        <!-- END Dynamic Table with Export Buttons -->
    </div>
    <!-- END Page Content -->
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/landing.blade.php
@extends('layouts.simple')
@section('content')
    <!-- Hero -->
    <div class="bg-image" style="background-image: url('{{ asset('media/photos/photo36@2x.jpg') }}');">
        <div class="hero bg-white overflow-hidden">
            <div class="hero-inner">
                <div class="content content-full text-center">
                    <h1 class="display-4 font-w600 mb-3 invisible" data-toggle="appear" data-class="animated fadeInDown">
                        GO BD <span class="text-primary font-w300">Logistics</span>
                    </h1>
                    <span class="m-2 d-inline-block invisible" data-toggle="appear" data-class="animated fadeInUp" data-timeout="600">
                        <a class="btn btn-success px-4 py-2" href="/login">
                            <i class="fa fa-fw fa-sign-in-alt mr-1"></i> Enter To Login
                        </a>
                    </span>
                </div>
            </div>
        </div>
    </div>
    <!-- END Hero -->
@endsection

resources/views/layouts/authentication_layout.blade.php
@include('layouts.partials.header')
<!-- Main Container -->
<main id="main-container">
    @yield('content')
</main>
<!-- END Main Container -->
@include('layouts.partials.footer')

resources/views/layouts/backend.blade.php
@include('layouts.partials.header')
@include('layouts.partials.sidebar')
<!-- Main Container -->
<main id="main-container">
    @yield('content')
</main>
<!-- END Main Container -->
@include('layouts.partials.footer')